### ISSUE TITLE
.editorconfig is not being picked up

### ISSUE THREAD

**Issue by perlun** [mikerochip/editorconfig-monodevelop#1]
Hi,

I'm having trouble getting the extension to work. Here is my config:

```
# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
```

This is in the same folder as my `.sln` file. I also tried copying it into the same folder as one of my `.csproj` files, to no avail.

Using VS for Mac 7.4 Enterprise (build 1033.) Extension was installed from the Gallery. Anything I need to configure to make it work?

Here is what is says in the About window:

```
Enabled user installed addins
EditorConfig 1.1
```

**Comment by mikerochip** [comment]
Does it work if you restart? There's a limitation where the addin needs to be already installed on startup to work. I'm actually not certain how to work around that.

**Comment by perlun** [comment]
@mikerochip Thanks, tried that already but it didnt. 😢 However, the "format document on save" setting seemed to do the trick - now it trims trailing whitespace at least...

Thanks for the feedback, will be closing this for now.
